### PR TITLE
Update litepaper.md

### PR DESCRIPTION
**Pull request by panditdhamdhere**
update with minor typos
updated from "**containerd**" to "**containers**" at the [GenAI Agent Network](https://docs.gaianet.ai/litepaper) page.
image

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [PR summary agent](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by alabulei1** [comment]
Hi @panditdhamdhere 

Thanks for your PR. Containerd is another container runtime, so it's not a typo here. https://containerd.io/

**Comment by alabulei1** [comment]
Thanks for the other PRs. Since it's not a typo, I will close this PR.

**Comment by panditdhamdhere** [comment]
alright Thank you @alabulei1 🙏🏽

**Pull request closed without merging**
